[package]
name = "pdf_extract"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pdf-extract = "0.6.4"
serde = "1.0.139"
serde_json = "1.0.82"
